language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "codemastrs3"
  skip_cleanup: true
  region: us-east-1
  acl: public_read
  on:
    all_branches: true
notifications:
  slack: $SLACK_CHANNEL
  on_success: always